name: Run tests

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install Poetry
      run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    - name: Add Poetry to path
      run: echo "${HOME}/.poetry/bin" >> $GITHUB_PATH
    - name: Install yupi on venv
      run: |
        poetry export -f requirements.txt > requirements.txt
        python -m pip install -r requirements.txt
        poetry install
    - name: Install Pytest
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests
      run: poetry run pytest ./tests/
